name: Daily JBZD Scraper

# Uruchamiaj codziennie o 8:00 UTC (UTC+2 to 10:00 w Polsce latem)
on:
  schedule:
    - cron: "0 6 * * *"  # 6:00 UTC = 8:00 Polska zimą
  workflow_dispatch:   # pozwala uruchomić ręcznie

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp async-timeout tqdm

    - name: Run scraper
      run: |
        python test.py

    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ranking.jsonl
        git commit -m "Aktualizacja rankingu JBZD"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
